version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    platform: linux/amd64
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      LEVEL_NAME: xserver
    ports:
      - 19132:19132/udp
    volumes:
      - bds:/data
      # - ./resource_packs:/data/resource_packs
    stdin_open: true
    tty: true

volumes:
  bds: {}
